### ISSUE TITLE
Reset Button

### ISSUE THREAD

**Issue by ABalanuta** [OpenChirp/LoRaBug#1]
New version should include a on-board reboot button.

**Comment by linux4life798** [comment]
Is there some reason why mapping the current button to driverlib/sys_ctrl.h's SysCtrlSystemReset() function doesn't suffice?

We might be able to squeeze a small surface mount push button near the I/O header.

**Comment by ABalanuta** [comment]
It is not a dedicated HW reset button, we should put a small one like the one on the launchpad near the leds.

**Comment by linux4life798** [comment]
Yeah, but the Launchpad is a devkit.
You can also populate C76 and remove C58 to be able to hard reset via the FTDI DTR line.
The firefly doesn't have a reset.

**Comment by linux4life798** [comment]
My apologies, didn't mean to close that. I was trying to cancel my comment draft. Let me give it more thought.
